### PR TITLE
sqlite database engine

### PR DESCRIPTION
**Pull request by codegod100**
I factored all the filesystem read stuff into its own engine file and then referenced those methods from a common api file. I also added sqlite engine with interface to same common api. The methods get dispatched based on what your `STORAGE_ENGINE` env variable is set to. default is `file` which is vanilla agora. Not all the endpoints work yet but the old stuff doesn't break so might as well merge.

There is a schema file included to create your own sqlite database. I haven't written the importer yet for this schema but I've been putting test data in by hand to test results.

I also created https://github.com/flancian/agora-server/pull/78 which runs `black` python formatter. If you merge that PR first the diff on this one might be cleaner. If you choose to go that route it might conflict but I can always just rebase my branch off that merge commit so shouldn't be a problem regardless.

### CODE REVIEW

**Comment by flancian** [comment]
Thank you for this, this looks very promising! I like the approach of the independent implementations and STORAGE_ENGINE. Looking into merging manually as there's some conflicts but I expect this should work.

**Comment by codegod100** [comment]
I can fix merge conflicts. I have lots of git merge experience. This is expected behavior. I can just rebase on top of your merge and should be fine. I'll post a new commit here soon

**Comment by codegod100** [comment]
this can be merged

**Comment by flancian** [comment]
Thank you, I was meaning to do that but you beat me to it and it is much appreciated :)

**Pull request merged**
